# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test-lint-build
  - release
  - test
variables:
  GIT_SUBMODULE_STRATEGY: recursive
test-lint-build:
  stage: test-lint-build
  image: registry.mdcatapult.io/informatics/docker-images/ci/node:multiple-releases
  tags:
    - wopr
  artifacts:
    paths:
      - dist/*
      - dist-bio/*
  before_script:
    - apt-get -yqq update && apt-get upgrade -yqq chromium libxss1 xvfb
    - export CHROME_BIN=/usr/bin/chromium
    - npm install
  script:
    - cictl get increment tag=develop
    - npm run lint
    - npm run mocha
    - npm run test:ci

    # build biology version
    - npm run build:bio
    - npm run package
    - mv dist/ dist-bio/

    # build general version
    - npm run build
    - npm run package

  coverage: /Lines\s+:\s(\d+\.?\d*)%\s\(\s\d+\/\d+\s\)/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  script:
    - /scripts/release.sh -b -r develop -u 'dist/browser-plugin/web-ext-artifacts/aurac-*.zip'

bio-release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
      - wopr
  script:
      - /scripts/release.sh -b -r develop -u \
        --release-path-1='dist-bio/browser-plugin/web-ext-artifacts/aurac-*.zip' \
        --release-tag-1='bio'

  only:
    - master
  except:
    variables:
      - '$CI_COMMIT_MESSAGE =~ /^Setting version to.*/'
#sast:
#  stage: test
#include:
#  - template: Security/SAST.gitlab-ci.yml
