stages:
  - test-lint-build
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-lint-build:
  stage: test-lint-build
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  artifacts:
    paths:
      - dist/*
  before_script:
    - apt-get -yqq update && apt-get upgrade -yqq chromium
    - export CHROME_BIN=/usr/bin/chromium
    - npm install
  script:
    - npm run test:ci
    - npm run lint
    - npm run build
    - npm run mocha
    - npm run package
  coverage: /Lines\s+:\s(\d+\.?\d*)%\s\(\s\d+\/\d+\s\)/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/


release:
  stage: release
  image: registry.mdcatapult.io/informatics/docker-images/ci/node
  tags:
    - wopr
  script:
    - /scripts/release.sh -b -r develop -u 'dist/browser-plugin/web-ext-artifacts/aurac-*.zip'
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
