type EntityBlacklistMap = Record<string, boolean>

export const EntityTextBlacklist: EntityBlacklistMap = {
    proteins: true,
    protein : true,
    hub : true,
    via : true,
    tgn : true,
    'alternative name' : true,
    orf : true,
    golgi : true,
    'golgi apparatus' : true,
    ptm : true,
    vps : true,
    mass : true,
    'truncated n-terminus' : true,
    et : true,
    van : true,
    cell : true,
    'transmembrane proteins' : true,
    killer : true,
    'pdz domain' : true,
    step: true,
    coil: true,
    'virion assembly': true,
    oct: true,
    amigo: true,
    sera: true,
    'peptide 1': true,
    'peptide 2': true,
    dec: true,
    bs8: true,
    spatial: true,
    mice: true,
    fast: true,
    damage: true,
    wave: true,
    nat: true,
    med: true,
    annu: true,
    proc: true,
    traits: true,
    sino: true,
    tele: true,
    aid: true,
    yeast: true,
    'ubiquitin-like protein': true,
    tip: true,
    impact: true,
    top: true,
    star: true,
    stars: true,
    enigma: true,
    max: true,
    bar: true,
    bars: true,
    phd: true,
    soc: true,
    sur: true,
    sbi: true,
    trap: true,
    traps: true,
    fig: true,
    bright: true,
    fate: true,
    sharp: true,
    chip: true,
    flash: true,
    light: true,
    lab: true,
    past: true,
    'intracellular protein': true,
    mark: true,
    kit: true,
    prism: true,
    minor: true,
    prep: true,
    degs: true,
    mix: true,
    acta: true,
    map: true,
    scott: true,
    lind: true,

    
}

export const EntityGroupBlacklist: EntityBlacklistMap = {
    'gene or protein class': true,
}

export const AbbreviationsNotGeneNames: EntityBlacklistMap = {
    S1A: true,
    S1B: true,
    S1C: true,
    S1D: true,
    S1E: true,
    S1F: true,
    S2A: true,
    S2B: true,
    S2C: true,
    S2D: true,
    S2E: true,
    S2F: true,
    S3A: true,
    S3B: true,
    S3C: true,
    S3D: true,
    S3E: true,
    S3F: true,
    S4A: true,
    S4B: true,
    S4C: true,
    S4D: true,
    S4E: true,
    S4F: true,
    S5A: true,
    S5B: true,
    S5C: true,
    S5D: true,
    S5E: true,
    S5F: true,
    S6A: true,
    S6B: true,
    S6C: true,
    S6D: true,
    S6E: true,
    S6F: true,
    S1: true,
    S2: true,
    S3: true,
    S4: true,
    S5: true,
    S6: true,
    S7: true,
    S8: true,
    S9: true,
    S10: true,
    S11: true,
    S12: true,
    S13: true,
    S14: true,
    S15: true,
    S16: true,
    P0: true,
    PTM: true,
    SNX: true,
}
